sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PHAN_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - pecl install ast
  - composer install --prefer-dist

script:
  - make ci --keep-going --jobs

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - travis_retry php vendor/bin/codacycoverage clover build/logs/clover.xml
